<a href="https://colab.research.google.com/github/enochbayode/Used-Car-Price-Prediction/blob/main/Used_Car_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [384]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [385]:
train = pd.read_csv('train.csv')
train.head(20)

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500
5,5,Audi,A6 2.0T Sport,2018,40950,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,White,–,None reported,Yes,29950
6,6,Audi,A8 L 3.0T,2016,62200,Gasoline,333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Black,Black,None reported,Yes,28500
7,7,Chevrolet,Silverado 1500 1LZ,2016,102604,E85 Flex Fuel,355.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,White,Gray,None reported,Yes,12500
8,8,Ford,F-150 XLT,2020,38352,Gasoline,2.7L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,Snowflake White Pearl Metallic,Black,None reported,Yes,62890
9,9,BMW,M4 Base,2015,74850,Gasoline,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Black,Blue,None reported,Yes,4000
10,10,Chevrolet,Camaro 1LT,2011,212500,Gasoline,312.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,A/T,Blue,Gray,At least 1 accident or damage reported,Yes,7950
11,11,Tesla,Model S P100D,2015,81500,NaN,Electric Motor Electric Fuel System,1-Speed A/T,Gray,White,None reported,Yes,19000
12,12,Cadillac,Escalade ESV Platinum,2017,93971,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Black,None reported,Yes,51500
13,13,Audi,S4 3.0T Premium Plus,2013,60000,Gasoline,333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,At least 1 accident or damage reported,Yes,12300
14,14,Land,Rover Range Rover P530 SE SWB,2023,20000,Gasoline,523.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes,56900
15,15,Mercedes-Benz,AMG C 63 S,2017,41500,Gasoline,503.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,White,Black,None reported,Yes,44900
16,16,GMC,Yukon Denali,2021,15000,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,10-Speed A/T,Green,Beige,None reported,Yes,68500
17,17,Land,Rover Defender SE,2021,46100,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Gray,Black,None reported,Yes,55000
18,18,Toyota,Tundra SR5,2011,153250,Gasoline,310.0HP 4.6L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,Gray,Gray,At least 1 accident or damage reported,Yes,9999
19,19,Mercedes-Benz,AMG C 63 Base,2019,16002,Gasoline,469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,9-Speed A/T,White,Red,At least 1 accident or damage reported,Yes,46900

In [386]:
test = pd.read_csv('test.csv')
test.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,188533,Land,Rover LR2 Base,2015,98000,Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Beige,None reported,Yes
1,188534,Land,Rover Defender SE,2020,9142,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Silver,Black,None reported,Yes
2,188535,Ford,Expedition Limited,2022,28121,Gasoline,3.5L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,White,Ebony,None reported,NaN
3,188536,Audi,A6 2.0T Sport,2016,61258,Gasoline,2.0 Liter TFSI,Automatic,Silician Yellow,Black,None reported,NaN
4,188537,Audi,A6 2.0T Premium Plus,2018,59000,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,None reported,Yes

In [387]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  object
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(4), object(9)
memory usage: 18.7+ MB

In [388]:
train["is_train"] = 1
test["is_train"] = 0

In [389]:
# Drop target from train before merging
target = train["price"]
train = train.drop(columns=["price"])

In [390]:
# Merge
Data = pd.concat([train, test], axis=0)

In [391]:
def accident_col(df):
    Data['accident_dummy'] = Data['accident'].apply(lambda x: 0 if x == 'NONE REPORTED' else (1 if x == 'AT LEAST 1 ACCIDENT OR DAMAGE REPORTED' else None))
    return Data

In [392]:
def transmission_col(df):
    def classify_transmission(transmission):
        if 'M/T' in transmission or 'MT' in transmission or 'MANUAL' in transmission:
            return 'M/T'
        elif 'A/T' in transmission or 'AT' in transmission or 'AUTOMATIC' in transmission or 'CVT TRANSMISSION' in transmission:
            return 'A/T'
        else:
            return 'OTHER'

    Data['transmission'] = Data['transmission'].apply(classify_transmission)
    return df

In [393]:
def ext_and_int_col(df):

  Data['ext_col'] = Data['ext_col'].apply(lambda x: x if x in ["BLACK","WHITE","GRAY","SILVER","BLUE","RED","ORANGE","SNOWFLAKE WHITE PEARL METALLIC",
                                                               "RADIANT RED METALLIC II","GREEN","OBSIDIAN BLACK METALLIC" ] else 'OTHERS')

  Data['int_col'] = Data['int_col'].apply(lambda x: x if x in ['BLACK', "BEIGE", "GRAY","WHITE","BLUE","BROWN","GRAPHITE"] else 'OTHERS')

  return Data

In [394]:
def fuel_type_col(Data):

    # Data['fuel_type'] = Data['fuel_type'].replace({'HYBRID': 'HYBRID', 'PLUG-IN HYBRID': 'HYBRID','NOT SUPPORTED':'OTHER','–':'OTHER'})
    # return Data

    Data['fuel_type'] = Data['fuel_type'].replace({
        'GASOLINE/MILD ELECTRIC HYBRID': 'HYBRID',
        'GAS/ELECTRIC HYBRID': 'HYBRID',
        'PLUG-IN HYBRID': 'HYBRID',
        'HYBRID': 'HYBRID',
        'NOT SUPPORTED': 'OTHER',
        '–': 'OTHER'
    })

# I kept "Gasoline", "Diesel", "Electric", "Flex Fuel Capability" unchanged since they’re already clear.

In [395]:
print (Data['engine'])

0              172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel
1              252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel
2         320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...
3              420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel
4              208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
                                ...
125685        362.0HP 3.0L V6 Cylinder Engine Gasoline Fuel
125686                                      3.0 Liter Turbo
125687        333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel
125688        333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel
125689         355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel
Name: engine, Length: 314223, dtype: object

In [396]:
print(Data.columns)
print(Data["engine"].head())
print(type(Data["engine"]))

Index(['id', 'brand', 'model', 'model_year', 'milage', 'fuel_type', 'engine',
       'transmission', 'ext_col', 'int_col', 'accident', 'clean_title',
       'is_train'],
      dtype='object')
0         172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel
1         252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel
2    320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...
3         420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel
4         208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
Name: engine, dtype: object
<class 'pandas.core.series.Series'>

In [397]:
def engine_col(df):
    # Create hp column
    Data['hp'] = Data['engine'].str.extract(r'(\d+\.\d+)HP').astype(float, errors='ignore')

    # Create engine displacement
    Data['engine displacement'] = Data['engine'].str.extract(r'(\d+\.\d+)L')
    Data['engine displacement'] = Data['engine displacement'].fillna(Data['engine'].str.extract(r'(\d+\.\d+)LITER')[0])
    Data['engine displacement'] = Data['engine displacement'].astype(float, errors='ignore')

    # Create cylinder
    Data['cylinder'] = Data['engine'].str.extract(r'(\d+) CYLINDER')
    Data['cylinder'] = Data['cylinder'].fillna(Data['engine'].str.extract(r'V(\d)')[0])
    Data['cylinder'] = Data['cylinder'].astype('Int64', errors='ignore')

    # Create fuel type
    Data['fuel'] = Data['engine'].str.extract(r'(GASOLINE|DIESEL|ELECTRIC|HYBRID|GASOLINE/MILD ELECTRIC HYBRID|GAS/ELECTRIC HYBRID|FLEX FUEL CAPABILITY)')
    Data['fuel_type'] = Data['fuel_type'].combine_first(Data['fuel'])

    # Is it V type or not
    Data['is_v_engine'] = Data['engine'].str.contains(r'V\d+', case=False, na=False)

    # Create turbo
    Data['turbo'] = Data['engine'].str.contains('TWIN TURBO', case=False, na=False)

    # Create dohc
    Data['dohc'] = Data['engine'].str.contains('DOHC', case=False, na=False)

    # Create MPFI
    Data['mpfi'] = Data['engine'].str.contains('MPFI', case=False, na=False)

    # Create GDI
    Data['gdi'] = Data['engine'].str.contains('GDI', case=False, na=False)

    # Create PDI
    Data['pdi'] = Data['engine'].str.contains('PDI', case=False, na=False)

    # Create OHC
    Data['ohc'] = Data['engine'].str.contains('OHC', case=False, na=False)


    return Data

In [398]:
def fill_na(df, bugatti_avg_hp_external=1300):
    Data['hp'] = Data.groupby('brand')['hp'].transform(lambda x: x.fillna(x.mean()))
    Data.loc[(df['brand'] == 'BUGATTI') & (Data['hp'].isnull()), 'hp'] = bugatti_avg_hp_external

    most_common_fuel = df.groupby('brand')['fuel_type'].agg(lambda x: x.mode()[0] if not x.mode().empty else None)
    most_common_displacement = df.groupby('brand')['engine displacement'].agg(lambda x: x.mode()[0] if not x.mode().empty else None)
    most_common_cylinder = df.groupby('brand')['cylinder'].agg(lambda x: x.mode()[0] if not x.mode().empty else None)

    Data['fuel_type'] = Data.apply(
        lambda row: most_common_fuel[row['brand']] if pd.isna(row['fuel_type']) else row['fuel_type'],
        axis=1
    )

    Data['engine displacement'] = Data.apply(
        lambda row: most_common_displacement[row['brand']] if pd.isna(row['engine displacement']) else row['engine displacement'],
        axis=1
    )

    Data['cylinder'] = Data.apply(
        lambda row: most_common_cylinder[row['brand']] if pd.isna(row['cylinder']) else row['cylinder'],
        axis=1
    )

    Data['cylinder'] = Data.apply(
        lambda row: most_common_cylinder[row['brand']] if pd.isna(row['cylinder']) else row['cylinder'],
        axis=1
    )
    Data['accident_dummy'].fillna(0, inplace=True)

    if Data['cylinder'].isnull().any():
        most_common_cylinder_value = Data['cylinder'].mode()[0]
        Data['cylinder'].fillna(most_common_cylinder_value, inplace=True)

    return Data

In [399]:
def one_hot_encoding(Data):
    Data = pd.get_dummies(Data, columns=['brand', 'fuel_type', 'transmission', 'ext_col', 'int_col'], drop_first=False)
    return Data

In [400]:
def age_and_usage(Data):
    current_year = 2025
    Data['age'] = current_year - Data['model_year']

    Data['annual_km'] = Data.apply(
        lambda row: row['milage'] / row['age'] if row['age'] > 0 else row['milage'],
        axis=1
    )

    return Data

In [401]:
def clean_strings(Data):
    for col in Data.select_dtypes(include="object"):
        Data[col] = Data[col].astype(str).str.upper()
    return Data

In [402]:
def all_processing(Data, bugatti_avg_hp_external=800):
    Data = Data.drop(columns=['id', 'model', 'clean_title'])

    Data = Data.applymap(lambda x: x.upper() if isinstance(x, str) else x)

    # Apply uppercase only to object type columns
    # for col in Data.select_dtypes(include='object').columns:
    #     Data[col] = Data[col].apply(lambda x: x.upper() if isinstance(x, str) else x)

    Data = clean_strings(Data)

    Data = accident_col(Data)

    Data = transmission_col(Data)

    Data = ext_and_int_col(Data)

    Data = fuel_type_col(Data)

    Data = engine_col(Data)

    Data = fill_na(Data, bugatti_avg_hp_external)

    Data = one_hot_encoding(Data)

    Data = age_and_usage(Data)


    return Data

In [403]:
Data = all_processing(Data)
Data.head(20)

/tmp/ipython-input-1232404493.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  Data = Data.applymap(lambda x: x.upper() if isinstance(x, str) else x)
/tmp/ipython-input-113039690.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Data['accident_dummy'].fillna(0, inplace=True)
/tmp/ipython-input-113039690.py:28: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Data['accident_dummy'].fillna(0, inplace=True)
/tmp/ipython-input-113039690.py:32: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Data['cylinder'].fillna(most_common_cylinder_value, inplace=True)
/tmp/ipython-input-113039690.py:32: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Data['cylinder'].fillna(most_common_cylinder_value, inplace=True)

,id,model,model_year,milage,engine,accident,clean_title,is_train,accident_dummy,hp,...,transmission_OTHER,ext_col_BLACK,ext_col_BLUE,ext_col_OTHERS,int_col_BEIGE,int_col_BLACK,int_col_OTHERS,int_col_WHITE,age,annual_km
0,0,Cooper S Base,2007,213000,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,None reported,Yes,1,0,172.000000,...,False,False,False,True,False,False,True,False,18,11833.333333
1,1,LS V8,2002,143250,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,At least 1 accident or damage reported,Yes,1,0,252.000000,...,False,False,False,True,False,False,True,False,23,6228.260870
2,2,Silverado 2500 LT,2002,136731,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,None reported,Yes,1,0,320.000000,...,False,False,False,True,False,False,True,False,23,5944.826087
3,3,G90 5.0 Ultimate,2017,19500,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,None reported,Yes,1,0,420.000000,...,True,False,False,True,False,False,True,False,8,2437.500000
4,4,Metris Base,2021,7388,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,None reported,Yes,1,0,208.000000,...,False,False,False,True,False,False,True,False,4,1847.000000
5,5,A6 2.0T Sport,2018,40950,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,None reported,Yes,1,0,252.000000,...,False,False,False,True,False,False,True,False,7,5850.000000
6,6,A8 L 3.0T,2016,62200,333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,None reported,Yes,1,0,333.000000,...,False,False,False,True,False,False,True,False,9,6911.111111
7,7,Silverado 1500 1LZ,2016,102604,355.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,None reported,Yes,1,0,355.000000,...,False,False,False,True,False,False,True,False,9,11400.444444
8,8,F-150 XLT,2020,38352,2.7L V6 24V PDI DOHC Twin Turbo,None reported,Yes,1,0,344.988356,...,True,False,False,True,False,False,True,False,5,7670.400000
9,9,M4 Base,2015,74850,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,None reported,Yes,1,0,425.000000,...,True,False,False,True,False,False,True,False,10,7485.000000
10,10,Camaro 1LT,2011,212500,312.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,At least 1 accident or damage reported,Yes,1,0,312.000000,...,False,False,False,True,False,False,True,False,14,15178.571429
11,11,Model S P100D,2015,81500,Electric Motor Electric Fuel System,None reported,Yes,1,0,491.637934,...,False,False,False,True,False,False,True,False,10,8150.000000
12,12,Escalade ESV Platinum,2017,93971,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,None reported,Yes,1,0,420.000000,...,False,False,False,True,False,False,True,False,8,11746.375000
13,13,S4 3.0T Premium Plus,2013,60000,333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,At least 1 accident or damage reported,Yes,1,0,333.000000,...,False,False,False,True,False,False,True,False,12,5000.000000
14,14,Rover Range Rover P530 SE SWB,2023,20000,523.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,None reported,Yes,1,0,523.000000,...,False,False,False,True,False,False,True,False,2,10000.000000
15,15,AMG C 63 S,2017,41500,503.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,None reported,Yes,1,0,503.000000,...,False,False,False,True,False,False,True,False,8,5187.500000
16,16,Yukon Denali,2021,15000,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,None reported,Yes,1,0,420.000000,...,False,False,False,True,False,False,True,False,4,3750.000000
17,17,Rover Defender SE,2021,46100,395.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,None reported,Yes,1,0,395.000000,...,False,False,False,True,False,False,True,False,4,11525.000000
18,18,Tundra SR5,2011,153250,310.0HP 4.6L 8 Cylinder Engine Gasoline Fuel,At least 1 accident or damage reported,Yes,1,0,310.000000,...,False,False,False,True,False,False,True,False,14,10946.428571
19,19,AMG C 63 Base,2019,16002,469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,At least 1 accident or damage reported,Yes,1,0,469.000000,...,False,False,False,True,False,False,True,False,6,2667.000000

In [404]:
Data = Data.drop(columns=['fuel', 'engine', 'accident', 'clean_title'], )

In [405]:
# Split back
train_processed = Data[Data["is_train"] == 1].drop(columns=["is_train"])
test_processed = Data[Data["is_train"] == 0].drop(columns=["is_train"])

In [406]:
train_processed["price"] = target

In [327]:
%pip install catboost

Collecting catboost
  Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.2.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (8.5.0)
Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl (99.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 8.4 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.8

In [407]:
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

In [408]:
def model_create(Data, target='price', model_type='lightgbm'):
    X = Data.drop([target], axis=1)
    y = Data[target]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

    if  model_type == 'xgboost':
        model = XGBRegressor()
    elif model_type == 'lightgbm':
        model = LGBMRegressor(verbosity=-1)
    elif model_type == 'catboost':
        model = CatBoostRegressor(verbose=0)
    else:
        raise ValueError("Change it. ")
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    return model, X_train, X_test, y_train, y_test, y_pred

In [409]:
from sklearn.metrics import mean_squared_error

def calculate_rmse(y_true, y_pred):
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)

    return rmse

In [373]:
train_processed.head(20)

,id,model,model_year,milage,accident_dummy,hp,engine displacement,cylinder,is_v_engine,turbo,...,ext_col_BLACK,ext_col_BLUE,ext_col_OTHERS,int_col_BEIGE,int_col_BLACK,int_col_OTHERS,int_col_WHITE,age,annual_km,price
0,0,Cooper S Base,2007,213000,0,172.000000,1.6,6,False,False,...,False,False,True,False,False,True,False,18,11833.333333,4200
1,1,LS V8,2002,143250,0,252.000000,3.9,6,False,False,...,False,False,True,False,False,True,False,23,6228.260870,4999
2,2,Silverado 2500 LT,2002,136731,0,320.000000,5.3,6,False,False,...,False,False,True,False,False,True,False,23,5944.826087,13900
3,3,G90 5.0 Ultimate,2017,19500,0,420.000000,5.0,6,False,False,...,False,False,True,False,False,True,False,8,2437.500000,45000
4,4,Metris Base,2021,7388,0,208.000000,2.0,6,False,False,...,False,False,True,False,False,True,False,4,1847.000000,97500
5,5,A6 2.0T Sport,2018,40950,0,252.000000,2.0,6,False,False,...,False,False,True,False,False,True,False,7,5850.000000,29950
6,6,A8 L 3.0T,2016,62200,0,333.000000,3.0,6,True,False,...,False,False,True,False,False,True,False,9,6911.111111,28500
7,7,Silverado 1500 1LZ,2016,102604,0,355.000000,5.3,6,False,False,...,False,False,True,False,False,True,False,9,11400.444444,12500
8,8,F-150 XLT,2020,38352,0,344.988356,2.7,6,True,True,...,False,False,True,False,False,True,False,5,7670.400000,62890
9,9,M4 Base,2015,74850,0,425.000000,3.0,8,False,False,...,False,False,True,False,False,True,False,10,7485.000000,4000
10,10,Camaro 1LT,2011,212500,0,312.000000,3.6,6,True,False,...,False,False,True,False,False,True,False,14,15178.571429,7950
11,11,Model S P100D,2015,81500,0,491.637934,5.0,6,False,False,...,False,False,True,False,False,True,False,10,8150.000000,19000
12,12,Escalade ESV Platinum,2017,93971,0,420.000000,6.2,6,False,False,...,False,False,True,False,False,True,False,8,11746.375000,51500
13,13,S4 3.0T Premium Plus,2013,60000,0,333.000000,3.0,6,True,False,...,False,False,True,False,False,True,False,12,5000.000000,12300
14,14,Rover Range Rover P530 SE SWB,2023,20000,0,523.000000,4.4,6,False,False,...,False,False,True,False,False,True,False,2,10000.000000,56900
15,15,AMG C 63 S,2017,41500,0,503.000000,4.0,6,False,False,...,False,False,True,False,False,True,False,8,5187.500000,44900
16,16,Yukon Denali,2021,15000,0,420.000000,6.2,6,False,False,...,False,False,True,False,False,True,False,4,3750.000000,68500
17,17,Rover Defender SE,2021,46100,0,395.000000,3.0,6,False,False,...,False,False,True,False,False,True,False,4,11525.000000,55000
18,18,Tundra SR5,2011,153250,0,310.000000,4.6,6,False,False,...,False,False,True,False,False,True,False,14,10946.428571,9999
19,19,AMG C 63 Base,2019,16002,0,469.000000,4.0,6,False,False,...,False,False,True,False,False,True,False,6,2667.000000,46900

In [410]:
train_processed.drop(columns=['model'], inplace=True)

In [411]:
model, X_train, X_test, y_train, y_test, y_pred = model_create(train_processed, target='price', model_type='lightgbm')

In [334]:
%pip install bayesian-optimization

Collecting bayesian-optimization
  Downloading bayesian_optimization-3.1.0-py3-none-any.whl.metadata (11 kB)
Collecting colorama>=0.4.6 (from bayesian-optimization)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization) (2.0.2)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->bayesian-optimization) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->bayesian-optimization) (3.6.0)
Downloading bayesian_optimization-3.1.0-py3-none-any.whl (36 kB)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: colorama, bayesian-optimization
Successfully installed bayesian-optimization-3.1.0 colorama-0.4.6

In [335]:
%pip install scikit-optimize

Collecting scikit-optimize
  Downloading scikit_optimize-0.10.2-py2.py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (1.5.2)
Collecting pyaml>=16.9 (from scikit-optimize)
  Downloading pyaml-25.7.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (2.0.2)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (1.16.1)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (1.6.1)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (25.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from pyaml>=16.9->scikit-optimize) (6.0.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->scikit-optimize) (3.6.0)
Downloading scikit_optimize-0.10.2-py2.py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.8/107.8 kB 5.8 MB/s eta 0:00:00
Downloading pyaml-25.7.0-py3-none-any.whl (26 kB)
Installing collected packages: pyaml, scikit-optimize
Successfully installed pyaml-25.7.0 scikit-optimize-0.10.2

In [412]:
from bayes_opt import BayesianOptimization
from skopt import BayesSearchCV

def bayesian_hyperparameter_optimization(X_train, y_train, model_type):
    if model_type == 'lightgbm':
        model = LGBMRegressor(verbosity=-1)
        search_spaces = {
            'n_estimators': (30, 300),
            'learning_rate': (0.01, 0.2, 'log-uniform'),
            'num_leaves': (10, 100),
            'max_depth': (-1, 15),
        }

    elif model_type == 'xgboost':
        model = XGBRegressor()
        search_spaces = {
            'n_estimators': (100, 500),
            'learning_rate': (0.01, 0.3, 'log-uniform'),
            'max_depth': (3, 15),
            'min_child_weight': (1, 10)
        }

    elif model_type == 'catboost':
        model = CatBoostRegressor(verbose=0)
        search_spaces = {
            'iterations': (100, 500),
            'learning_rate': (0.01, 0.3, 'log-uniform'),
            'depth': (3, 15),
            'l2_leaf_reg': (1, 10)
        }

    else:
        raise ValueError("Change it.")

    opt = BayesSearchCV(model, search_spaces, n_iter=32, cv=5, scoring='neg_mean_squared_error', n_jobs=-1,random_state=42)
    opt.fit(X_train, y_train)

    return opt.best_estimator_, opt.best_params_

In [413]:
best_model, best_params = bayesian_hyperparameter_optimization(X_train, y_train, model_type='lightgbm')
print("The best model:", best_model)
print("The best parameters:", best_params)

The best model: LGBMRegressor(learning_rate=0.16231042492897596, max_depth=2, n_estimators=300,
              num_leaves=99, verbosity=-1)
The best parameters: OrderedDict({'learning_rate': 0.16231042492897596, 'max_depth': 2, 'n_estimators': 300, 'num_leaves': 99})

In [414]:
y_pred_best = best_model.predict(X_test)

In [415]:
calculate_rmse(y_test,y_pred_best)

np.float64(69382.19398328563)

In [416]:
print(test_processed.shape)
print(test_processed.head())

(125690, 91)
       id                 model  model_year  milage  accident_dummy  \
0  188533        Rover LR2 Base        2015   98000               0
1  188534     Rover Defender SE        2020    9142               0
2  188535    Expedition Limited        2022   28121               0
3  188536         A6 2.0T Sport        2016   61258               0
4  188537  A6 2.0T Premium Plus        2018   59000               0

           hp  engine displacement  cylinder  is_v_engine  turbo  ...  \
0  240.000000                  2.0         6        False  False  ...
1  395.000000                  3.0         6        False  False  ...
2  344.988356                  3.5         6         True   True  ...
3  307.614712                  2.0         6        False  False  ...
4  252.000000                  2.0         6        False  False  ...

   transmission_OTHER  ext_col_BLACK  ext_col_BLUE  ext_col_OTHERS  \
0               False          False         False            True
1               False          False         False            True
2                True          False         False            True
3                True          False         False            True
4               False          False         False            True

   int_col_BEIGE  int_col_BLACK  int_col_OTHERS  int_col_WHITE  age  \
0          False          False            True          False   10
1          False          False            True          False    5
2          False          False            True          False    3
3          False          False            True          False    9
4          False          False            True          False    7

     annual_km
0  9800.000000
1  1828.400000
2  9373.666667
3  6806.444444
4  8428.571429

[5 rows x 91 columns]

In [417]:
test_processed.drop(columns=['model'], inplace=True)

In [418]:
y_test_pred = best_model.predict(test_processed)

In [419]:
submission=pd.DataFrame({"id":test_processed['id'],"Price":y_test_pred})
submission.to_csv("Submission5.csv",index=False)